### ISSUE TITLE
Share hex length is (I think) always invalid (odd)

### ISSUE THREAD

**Issue by jgeewax** [amper5and/secrets.js#8]
The issue looks to be with the prefixing, which always appends an "8" (https://github.com/amper5and/secrets.js/blob/master/secrets.js#L246)

From what I can see, the following lines aren't quite right:

```js
for(var i=0; i<numShares; i++){
    x[i] = config.bits.toString(36).toUpperCase() + padLeft(x[i],padding) + bin2hex(y[i]);
}
```

1. Why are we using base 36? For a larger number than 8, (ie, 200), there's no way that this will generate a valid hexadecimal value... (`(200).toString(36) == '5k'`)

1. Assuming we meant this to be `16` instead of `36` (which makes much more sense), it still can result in an odd-length string, which is :-1: (`(8).toString(16) == '8'`)
  - To illustrate why this is a bad time, here's a traceback:
  ```js
  > new Buffer((8).toString(16), 'hex');
TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:568:21)
    at fromString (buffer.js:115:26)
    at new Buffer (buffer.js:54:12)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
  ```

I *think* we should do what you did a bit later in the line with `padLeft`:

```js
for(var i = 0; i < numShares; i++) {
    // x[i] is (even-length number of bits, any padding requested, and then the secret share)
    var prefix = padLeft(config.bits.toString(16).toUpperCase(), 2),
        padding = padLeft(x[i], padding);
    x[i] = prefix + padding + bin2hex(y[i]);
}
```

**Comment by grempe** [comment]
@jgeewax I wonder if you would be interested in taking a look at my fork of this project and seeing if you have similar issues still there.  I don't think any changes have been accepted on this project for a couple of years. I did a pretty major revamp on the fork and perhaps it resolved your issues.  I would certainly take a look at pull requests if there is an issue you are still seeing.

https://github.com/grempe/secrets.js

Glenn

**Comment by amper5and** [comment]
So, I know I haven't worked on this project in years, but just glancing through your comments, I wanted to point a few things out. Most of this is obvious from the readme btw:

> Why are we using base 36? For a larger number than 8, (ie, 200), there's no way that this will generate a valid hexadecimal value... ((200).toString(36) == '5k')

secrets.js only uses Galois fields between 2^3 and 2^20, so the `bits` accepted must be between 3 and 20. In the interest of using ONE character for the bit-field in the final share, base-36 was selected, to encode all possible values using the characters [3-9, a-k].

> The issue looks to be with the prefixing, which always appends an "8" (https://github.com/amper5and/secrets.js/blob/master/secrets.js#L246)

The 8 is appended because an 8-bit field is used by default. You can change config.bits to something other than 8, and you'll have that value appended
